; ============================================================================
;  FDM - Fast Download Manager :: Windows installer
;  Inno Setup 6.3 or newer (needs DownloadTemporaryFile, added in 6.1).
;
;  This is the ONE file an end user ever touches. Compiling this script produces
;  FDM-Setup-<version>.exe, and running that must leave a machine with a working
;  FDM regardless of what was or wasn't already installed. Everything it needs
;  and cannot assume, it fetches.
;
;  Build with:  powershell -ExecutionPolicy Bypass -File scripts\build-installer.ps1
;
;  ASCII only, on purpose: this file has no BOM, and ISCC misreads high bytes in
;  a BOM-less file. That is why the product name uses "-" and not an em dash.
; ============================================================================

#define AppName        "FDM - Fast Download Manager"
#define AppShortName   "FDM"
#define AppPublisher   "Ahmad Farooq"
#define AppUrl         "https://github.com/ahmadfarooq/fdm"
#define AppSupportUrl  "https://github.com/ahmadfarooq/fdm/issues"
#define AppExeName     "fdm-desktop.exe"
#define HostExeName    "fdm-host.exe"
#define CliExeName     "fdm.exe"
#define NativeHostName "com.fdm.native_host"

; Overridable from the command line: ISCC /DAppVersion=0.2.0 installer\fdm.iss
#ifndef AppVersion
  #define AppVersion "0.1.0"
#endif

; Where build-installer.ps1 assembles the payload.
#ifndef StagingDir
  #define StagingDir "..\target\installer-staging"
#endif

; The Chrome Web Store extension ID. Unknown until the extension is published --
; Chrome derives it from the signing key the Store assigns. Until then the
; browser-registration block below is compiled out rather than writing a junk
; registry key that would make Chrome log an error on every launch.
#ifndef ChromeExtensionId
  #define ChromeExtensionId "enipidhffjdkkkmmohnnehfdigdnmfeo"
#endif
#define ExtensionPublished (ChromeExtensionId != "UNPUBLISHED")

; Evergreen WebView2 bootstrapper. Permanent Microsoft fwlink, ~1.8 MB; it then
; pulls the full runtime itself. Deliberately not SHA-256 pinned: Microsoft
; reissues this file, and a pinned hash would turn every reissue into a broken
; installer for every user at once. The URL is HTTPS to a Microsoft host and the
; payload is Authenticode-signed by Microsoft, which is the real integrity gate.
#define WebView2Url "https://go.microsoft.com/fwlink/p/?LinkId=2124703"

[Setup]
; Never change AppId. It is how Windows recognises an upgrade rather than a
; second parallel installation.
AppId={{8B7F3A21-4D6E-4C1B-9E5A-2F0D7C6B4A19}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription={#AppName} Setup
AppPublisher={#AppPublisher}
AppPublisherURL={#AppUrl}
AppSupportURL={#AppSupportUrl}
AppUpdatesURL={#AppUrl}/releases
DefaultDirName={autopf}\FDM
DefaultGroupName=FDM
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\fdm.ico
LicenseFile=..\LICENSE
InfoAfterFile=..\NOTICE
OutputDir=output
OutputBaseFilename=FDM-Setup-{#AppVersion}
SetupIconFile=assets\fdm.ico
WizardStyle=modern
WizardImageFile=assets\wizard-large.bmp
WizardSmallImageFile=assets\wizard-small.bmp
WizardImageStretch=no

; Admin: the native messaging host and the browser extension policy both live
; under HKLM. A per-user install would have to write HKCU, which breaks the
; moment the browser runs under a different integrity level.
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; If FDM is running, close it rather than leaving locked files behind. The mutex
; name must match the one the desktop app creates for single-instance.
AppMutex=FdmSingleInstanceMutex
CloseApplications=yes
RestartApplications=no

Compression=lzma2/max
SolidCompression=yes
LZMAUseSeparateProcess=yes
DisableProgramGroupPage=yes
DisableDirPage=no
; Ask which language to install in, and preselect the one matching Windows so
; most users can just press Enter. Was `no` back when English was the only
; option — leaving it that way would have compiled fifteen translations in and
; then never offered any of them.
ShowLanguageDialog=yes
LanguageDetectionMethod=uilanguage
MinVersion=10.0.17763

; Code signing. Enabled by build-installer.ps1 -SignThumbprint / -SelfSign,
; which passes /DSignToolName=fdmsign together with /Sfdmsign="<command>".
;
; This block exists for one reason: the uninstaller. Setup.exe can be signed
; afterwards with signtool, but unins000.exe is generated by Setup at install
; time on the user's machine, so only Inno can arrange for it to be signed --
; it embeds a pre-signed copy. Without this, Add/Remove Programs > Uninstall
; raises a UAC prompt reading "Publisher: Unknown" even on a signed install.
#ifdef SignToolName
SignTool={#SignToolName}
SignedUninstaller=yes
#endif

; Setup asks which language to use before the first wizard page. These are the
; translations Inno Setup ships; the app's own UI language is separate and lives
; in Settings, because a user who installs in English may still want the app in
; their own language (and vice versa).
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

; Our own wizard strings, per language. Anything a translation does not define
; falls back to the english entry.
[CustomMessages]
english.TaskDesktopIcon=Create a &desktop shortcut
english.TaskStartup=Start FDM when I sign in to Windows
english.TaskAddToPath=Add the &fdm command to PATH (for terminal use)
english.GroupShortcuts=Shortcuts:
english.GroupStartup=Startup:
english.GroupAdvanced=Advanced:

arabic.TaskDesktopIcon=إنشاء اختصار على &سطح المكتب
arabic.TaskStartup=تشغيل FDM عند تسجيل الدخول إلى Windows
arabic.TaskAddToPath=إضافة الأمر &fdm إلى PATH (للاستخدام من الطرفية)
arabic.GroupShortcuts=الاختصارات:
arabic.GroupStartup=بدء التشغيل:
arabic.GroupAdvanced=متقدم:

czech.TaskDesktopIcon=Vytvořit zástupce na &ploše
czech.TaskStartup=Spouštět FDM při přihlášení do Windows
czech.TaskAddToPath=Přidat příkaz &fdm do PATH (pro terminál)
czech.GroupShortcuts=Zástupci:
czech.GroupStartup=Po spuštění:
czech.GroupAdvanced=Pokročilé:

dutch.TaskDesktopIcon=Een snelkoppeling op het &bureaublad maken
dutch.TaskStartup=FDM starten wanneer ik me aanmeld bij Windows
dutch.TaskAddToPath=De opdracht &fdm aan PATH toevoegen (voor de terminal)
dutch.GroupShortcuts=Snelkoppelingen:
dutch.GroupStartup=Opstarten:
dutch.GroupAdvanced=Geavanceerd:

french.TaskDesktopIcon=Créer un raccourci sur le &Bureau
french.TaskStartup=Lancer FDM à l'ouverture de session Windows
french.TaskAddToPath=Ajouter la commande &fdm au PATH (pour le terminal)
french.GroupShortcuts=Raccourcis :
french.GroupStartup=Démarrage :
french.GroupAdvanced=Avancé :

german.TaskDesktopIcon=Verknüpfung auf dem &Desktop erstellen
german.TaskStartup=FDM bei der Anmeldung bei Windows starten
german.TaskAddToPath=Befehl &fdm zum PATH hinzufügen (für das Terminal)
german.GroupShortcuts=Verknüpfungen:
german.GroupStartup=Autostart:
german.GroupAdvanced=Erweitert:

italian.TaskDesktopIcon=Crea un collegamento sul &desktop
italian.TaskStartup=Avvia FDM all'accesso a Windows
italian.TaskAddToPath=Aggiungi il comando &fdm al PATH (per il terminale)
italian.GroupShortcuts=Collegamenti:
italian.GroupStartup=Avvio:
italian.GroupAdvanced=Avanzate:

japanese.TaskDesktopIcon=デスクトップにショートカットを作成する(&D)
japanese.TaskStartup=Windows へのサインイン時に FDM を起動する
japanese.TaskAddToPath=PATH に &fdm コマンドを追加する (ターミナル用)
japanese.GroupShortcuts=ショートカット:
japanese.GroupStartup=スタートアップ:
japanese.GroupAdvanced=詳細設定:

korean.TaskDesktopIcon=바탕 화면에 바로 가기 만들기(&D)
korean.TaskStartup=Windows에 로그인할 때 FDM 시작
korean.TaskAddToPath=PATH에 &fdm 명령 추가 (터미널용)
korean.GroupShortcuts=바로 가기:
korean.GroupStartup=시작 프로그램:
korean.GroupAdvanced=고급:

polish.TaskDesktopIcon=Utwórz skrót na &pulpicie
polish.TaskStartup=Uruchamiaj FDM po zalogowaniu do Windows
polish.TaskAddToPath=Dodaj polecenie &fdm do PATH (do użytku w terminalu)
polish.GroupShortcuts=Skróty:
polish.GroupStartup=Autostart:
polish.GroupAdvanced=Zaawansowane:

portuguese.TaskDesktopIcon=Criar um atalho na &área de trabalho
portuguese.TaskStartup=Iniciar o FDM ao entrar no Windows
portuguese.TaskAddToPath=Adicionar o comando &fdm ao PATH (para o terminal)
portuguese.GroupShortcuts=Atalhos:
portuguese.GroupStartup=Inicialização:
portuguese.GroupAdvanced=Avançado:

russian.TaskDesktopIcon=Создать ярлык на &рабочем столе
russian.TaskStartup=Запускать FDM при входе в Windows
russian.TaskAddToPath=Добавить команду &fdm в PATH (для терминала)
russian.GroupShortcuts=Ярлыки:
russian.GroupStartup=Автозапуск:
russian.GroupAdvanced=Дополнительно:

spanish.TaskDesktopIcon=Crear un acceso directo en el &escritorio
spanish.TaskStartup=Iniciar FDM al iniciar sesión en Windows
spanish.TaskAddToPath=Añadir el comando &fdm al PATH (para la terminal)
spanish.GroupShortcuts=Accesos directos:
spanish.GroupStartup=Inicio:
spanish.GroupAdvanced=Avanzado:

turkish.TaskDesktopIcon=&Masaüstü kısayolu oluştur
turkish.TaskStartup=Windows'a giriş yaptığımda FDM'yi başlat
turkish.TaskAddToPath=&fdm komutunu PATH'e ekle (terminal için)
turkish.GroupShortcuts=Kısayollar:
turkish.GroupStartup=Başlangıç:
turkish.GroupAdvanced=Gelişmiş:

ukrainian.TaskDesktopIcon=Створити ярлик на &робочому столі
ukrainian.TaskStartup=Запускати FDM під час входу у Windows
ukrainian.TaskAddToPath=Додати команду &fdm до PATH (для термінала)
ukrainian.GroupShortcuts=Ярлики:
ukrainian.GroupStartup=Автозапуск:
ukrainian.GroupAdvanced=Додатково:

[Tasks]
Name: "desktopicon"; Description: "{cm:TaskDesktopIcon}"; GroupDescription: "{cm:GroupShortcuts}"
Name: "startup"; Description: "{cm:TaskStartup}"; GroupDescription: "{cm:GroupStartup}"
Name: "addtopath"; Description: "{cm:TaskAddToPath}"; GroupDescription: "{cm:GroupAdvanced}"; Flags: unchecked

[Files]
; --- Engine and CLI. Always present; the build script refuses to run without it.
Source: "{#StagingDir}\{#CliExeName}"; DestDir: "{app}"; Flags: ignoreversion

; --- Desktop app and native messaging host. Marked skipifsourcedoesntexist so
;     this script compiles during Phase 1/2 development; build-installer.ps1
;     prints exactly which of them made it into a given build, and refuses to
;     produce a release build without them.
Source: "{#StagingDir}\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#StagingDir}\{#HostExeName}"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#StagingDir}\WebView2Loader.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist

; --- Unpacked extension. Ships even when the Store version is registered: it is
;     the fallback for Chromium builds without Store access, and the thing a
;     developer loads via chrome://extensions -> Load unpacked.
Source: "{#StagingDir}\extension\*"; DestDir: "{app}\extension"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist

; --- Video extractor & JS runtime tools (yt-dlp, deno)
Source: "{#StagingDir}\tools\*"; DestDir: "{app}\tools"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist

Source: "assets\fdm.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\LICENSE"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion
Source: "..\NOTICE"; DestDir: "{app}"; DestName: "NOTICE.txt"; Flags: ignoreversion
Source: "..\README.md"; DestDir: "{app}"; DestName: "README.md"; Flags: ignoreversion skipifsourcedoesntexist

[Dirs]
; The generated native messaging manifest lands here.
Name: "{app}\manifests"

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\fdm.ico"; Check: HasDesktopApp
Name: "{group}\Uninstall {#AppShortName}"; Filename: "{uninstallexe}"; IconFilename: "{app}\fdm.ico"
Name: "{autodesktop}\{#AppShortName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\fdm.ico"; Tasks: desktopicon; Check: HasDesktopApp

[Registry]
; ---------------------------------------------------------------- uninstall key
Root: HKLM; Subkey: "Software\FDM"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"; Flags: uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\FDM"; ValueType: string; ValueName: "Version"; ValueData: "{#AppVersion}"; Flags: uninsdeletekey

; ------------------------------------------------- native messaging host, HKLM & HKCU
; One key per Chromium family. They do not share a namespace, so a user on Brave
; gets nothing from the Chrome key. All point at the same generated manifest.
Root: HKLM32; Subkey: "Software\Google\Chrome\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\Google\Chrome\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKCU; Subkey: "Software\Google\Chrome\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost

Root: HKLM32; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKCU; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost

Root: HKLM64; Subkey: "Software\BraveSoftware\Brave-Browser\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKCU; Subkey: "Software\BraveSoftware\Brave-Browser\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost

Root: HKLM64; Subkey: "Software\Vivaldi\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\Chromium\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost

; ------------------------------------------------------- extension auto-install (Policy & Registry)
Root: HKLM; Subkey: "Software\Policies\Google\Chrome\ExtensionInstallForcelist"; ValueType: string; ValueName: "1"; ValueData: "{#ChromeExtensionId};file:///{app}\extension\update.xml"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Policies\Google\Chrome\ExtensionInstallSources"; ValueType: string; ValueName: "1"; ValueData: "file:///*"; Flags: uninsdeletevalue

Root: HKLM; Subkey: "Software\Policies\Microsoft\Edge\ExtensionInstallForcelist"; ValueType: string; ValueName: "1"; ValueData: "{#ChromeExtensionId};file:///{app}\extension\update.xml"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Policies\Microsoft\Edge\ExtensionInstallSources"; ValueType: string; ValueName: "1"; ValueData: "file:///*"; Flags: uninsdeletevalue

Root: HKLM; Subkey: "Software\Policies\BraveSoftware\Brave-Browser\ExtensionInstallForcelist"; ValueType: string; ValueName: "1"; ValueData: "{#ChromeExtensionId};file:///{app}\extension\update.xml"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Policies\BraveSoftware\Brave-Browser\ExtensionInstallSources"; ValueType: string; ValueName: "1"; ValueData: "file:///*"; Flags: uninsdeletevalue

Root: HKLM32; Subkey: "Software\Google\Chrome\Extensions\{#ChromeExtensionId}"; ValueType: string; ValueName: "path"; ValueData: "{app}\extension\fdm.crx"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Google\Chrome\Extensions\{#ChromeExtensionId}"; ValueType: string; ValueName: "path"; ValueData: "{app}\extension\fdm.crx"; Flags: uninsdeletekey
Root: HKLM32; Subkey: "Software\Google\Chrome\Extensions\{#ChromeExtensionId}"; ValueType: string; ValueName: "version"; ValueData: "{#AppVersion}"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Google\Chrome\Extensions\{#ChromeExtensionId}"; ValueType: string; ValueName: "version"; ValueData: "{#AppVersion}"; Flags: uninsdeletekey

; ------------------------------------------------------------------- run-at-login
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "FDM"; ValueData: """{app}\{#AppExeName}"" --background"; Flags: uninsdeletevalue; Tasks: startup; Check: HasDesktopApp

; ------------------------------------------------------------------------- PATH
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Tasks: addtopath; Check: NeedsAddPath(ExpandConstant('{app}'))

[Run]
; Create Downloads\FDM\{Documents,Video,Music,Images,Compressed,Programs,Other}.
; runasoriginaluser is the whole point: without it the folders would be created
; in the elevating administrator's profile, not the user's.
Filename: "{app}\{#CliExeName}"; Parameters: "init-folders"; Flags: runasoriginaluser runhidden waituntilterminated; StatusMsg: "Creating your download folders..."

Filename: "{app}\{#AppExeName}"; Description: "Launch {#AppShortName} now"; Flags: nowait postinstall skipifsilent runasoriginaluser; Check: HasDesktopApp
Filename: "https://github.com/ahmadfarooq/fdm#enabling-the-browser-extension"; Description: "Show me how to enable the browser extension"; Flags: nowait postinstall shellexec skipifsilent unchecked

[UninstallDelete]
; Generated at install time, so not tracked by the file list.
Type: files; Name: "{app}\manifests\{#NativeHostName}.json"
Type: dirifempty; Name: "{app}\manifests"
Type: dirifempty; Name: "{app}"

; Unscoped entries apply to every language, so English stays the fallback for
; the translations below that are not overridden — losing the Chrome extension
; instruction would cost a user a working browser integration, which is worse
; than reading it in English.
[Messages]
WelcomeLabel2=This will install [name/ver] on your computer.%n%nFDM splits every download across many connections and writes them straight to disk, so there is no reassembly step and a crash resumes instead of restarting.%n%nSetup will also install anything missing that FDM needs, including the Microsoft WebView2 runtime.
FinishedLabelNoIcons=Setup finished installing [name].
FinishedLabel=Setup finished installing [name].%n%nOne last step, and it is Chrome's rule rather than ours: open your browser and click Enable when it asks about the FDM extension. Chrome does not allow any installer to enable an extension for you.

arabic.WelcomeLabel2=سيتم تثبيت [name/ver] على جهازك.%n%nيقسّم FDM كل عملية تنزيل عبر اتصالات متعددة ويكتبها مباشرة على القرص، فلا توجد مرحلة إعادة تجميع، وأي انقطاع يُستأنف بدل أن يبدأ من جديد.%n%nسيثبّت الإعداد أيضاً كل ما ينقص FDM، بما في ذلك بيئة تشغيل Microsoft WebView2.
arabic.FinishedLabel=انتهى تثبيت [name].%n%nخطوة أخيرة، وهي من قواعد Chrome وليست منّا: افتح المتصفح وانقر «تمكين» عندما يسألك عن إضافة FDM. لا يسمح Chrome لأي مثبِّت بتمكين إضافة نيابةً عنك.

french.WelcomeLabel2=[name/ver] va être installé sur votre ordinateur.%n%nFDM répartit chaque téléchargement sur de nombreuses connexions et écrit directement sur le disque : aucune étape de réassemblage, et une coupure reprend au lieu de tout recommencer.%n%nLe programme d'installation ajoutera également ce qui manque à FDM, y compris le runtime Microsoft WebView2.
french.FinishedLabel=L'installation de [name] est terminée.%n%nUne dernière étape, imposée par Chrome et non par nous : ouvrez votre navigateur et cliquez sur Activer lorsqu'il vous interroge sur l'extension FDM. Chrome n'autorise aucun installateur à activer une extension à votre place.

german.WelcomeLabel2=[name/ver] wird auf Ihrem Computer installiert.%n%nFDM verteilt jeden Download auf viele Verbindungen und schreibt ihn direkt auf die Festplatte — kein Zusammensetzen am Ende, und ein Abbruch wird fortgesetzt statt neu gestartet.%n%nSetup installiert außerdem alles Fehlende, was FDM benötigt, einschließlich der Microsoft-WebView2-Laufzeit.
german.FinishedLabel=Die Installation von [name] ist abgeschlossen.%n%nEin letzter Schritt, und das ist Chromes Regel, nicht unsere: Öffnen Sie Ihren Browser und klicken Sie auf Aktivieren, wenn er nach der FDM-Erweiterung fragt. Chrome erlaubt es keinem Installationsprogramm, eine Erweiterung für Sie zu aktivieren.

portuguese.WelcomeLabel2=O [name/ver] será instalado no seu computador.%n%nO FDM divide cada download em várias conexões e grava direto no disco, por isso não há etapa de remontagem e uma queda continua em vez de recomeçar.%n%nA instalação também adicionará o que faltar ao FDM, incluindo o runtime Microsoft WebView2.
portuguese.FinishedLabel=A instalação do [name] foi concluída.%n%nFalta um passo, e é regra do Chrome, não nossa: abra o navegador e clique em Ativar quando ele perguntar sobre a extensão do FDM. O Chrome não permite que nenhum instalador ative uma extensão por você.

russian.WelcomeLabel2=На ваш компьютер будет установлен [name/ver].%n%nFDM разбивает каждую загрузку на множество соединений и пишет их прямо на диск, поэтому нет этапа сборки, а обрыв продолжается с места остановки, а не начинается заново.%n%nУстановщик также добавит всё недостающее, включая среду выполнения Microsoft WebView2.
russian.FinishedLabel=Установка [name] завершена.%n%nОстался последний шаг, и это правило Chrome, а не наше: откройте браузер и нажмите «Включить», когда он спросит о расширении FDM. Chrome не позволяет установщику включить расширение за вас.

spanish.WelcomeLabel2=Se instalará [name/ver] en su equipo.%n%nFDM reparte cada descarga entre muchas conexiones y la escribe directamente en disco, así que no hay fase de reensamblado y un corte se reanuda en lugar de empezar de nuevo.%n%nEl instalador añadirá además lo que le falte a FDM, incluido el entorno de ejecución Microsoft WebView2.
spanish.FinishedLabel=La instalación de [name] ha finalizado.%n%nQueda un último paso, y es norma de Chrome, no nuestra: abra el navegador y haga clic en Activar cuando le pregunte por la extensión de FDM. Chrome no permite que ningún instalador active una extensión por usted.

turkish.WelcomeLabel2=[name/ver] bilgisayarınıza kurulacak.%n%nFDM her indirmeyi birçok bağlantıya böler ve doğrudan diske yazar; birleştirme aşaması yoktur ve kesinti baştan başlamak yerine kaldığı yerden devam eder.%n%nKurulum ayrıca Microsoft WebView2 çalışma zamanı dahil, FDM'nin eksik olan gereksinimlerini de yükler.
turkish.FinishedLabel=[name] kurulumu tamamlandı.%n%nSon bir adım kaldı ve bu bizim değil Chrome'un kuralı: tarayıcınızı açın ve FDM uzantısını sorduğunda Etkinleştir'e tıklayın. Chrome hiçbir kurulum programının sizin yerinize bir uzantıyı etkinleştirmesine izin vermez.

[Code]
{ ISPP treats any line whose first non-whitespace character is '#' as a
  preprocessor directive -- including inside [Code]. A wrapped Pascal expression
  that happens to begin with #13#10 therefore fails to compile with "Unknown
  preprocessor directive". Naming the newline once avoids the trap entirely. }
const
  NL = #13#10;

var
  DownloadPage: TDownloadWizardPage;

{ ------------------------------------------------------------------ payload probes }
{ The desktop app and native host are built in later phases. Rather than shipping
  shortcuts to a file that isn't there, every dependent entry is gated on the
  file actually having been installed. }

function HasDesktopApp: Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\{#AppExeName}'));
end;

function HasNativeHost: Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\{#HostExeName}'));
end;

{ --------------------------------------------------------------------------- PATH }

function NeedsAddPath(Param: String): Boolean;
var
  OrigPath: String;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath) then
  begin
    Result := True;
    exit;
  end;
  { Semicolon-delimited on both sides so "C:\Program Files\FDM" does not match
    "C:\Program Files\FDMx". }
  Result := Pos(';' + Uppercase(Param) + ';', ';' + Uppercase(OrigPath) + ';') = 0;
end;

{ ---------------------------------------------------------------- WebView2 runtime }
{ The Evergreen runtime registers its version under EdgeUpdate Clients with this
  fixed GUID. Machine-wide installs land in HKLM (and in the 32-bit view even on
  64-bit Windows); per-user installs land in HKCU. A non-empty 'pv' means present.
  Windows 11 ships it, so on most machines this returns True and nothing is
  downloaded at all. }

function WebView2Installed: Boolean;
var
  Version: String;
  ClientKey: String;
begin
  Result := False;
  { The Evergreen runtime's fixed product GUID. Not a placeholder -- Microsoft
    ships this exact value on every machine that has WebView2. }
  ClientKey := 'Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';

  if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\WOW6432Node\' + ClientKey, 'pv', Version) then
    if (Version <> '') and (Version <> '0.0.0.0') then
    begin
      Result := True;
      exit;
    end;

  if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\' + ClientKey, 'pv', Version) then
    if (Version <> '') and (Version <> '0.0.0.0') then
    begin
      Result := True;
      exit;
    end;

  if RegQueryStringValue(HKEY_CURRENT_USER, 'SOFTWARE\' + ClientKey, 'pv', Version) then
    if (Version <> '') and (Version <> '0.0.0.0') then
      Result := True;
end;

{ ------------------------------------------------- native messaging host manifest }
{ Written at install time rather than shipped, because 'path' has to be the real
  absolute install path and 'allowed_origins' has to match the published
  extension ID. Chrome refuses to start a host whose manifest lists an origin
  that does not match the calling extension, so a wrong value here is a silent
  "extension can't reach FDM" bug. }

procedure WriteNativeHostManifest;
var
  Lines: TArrayOfString;
  HostPath: String;
  Dir: String;
begin
  if not HasNativeHost then
    exit;

  Dir := ExpandConstant('{app}\manifests');
  if not DirExists(Dir) then
    ForceDirectories(Dir);

  { JSON needs backslashes escaped. }
  HostPath := ExpandConstant('{app}\{#HostExeName}');
  StringChangeEx(HostPath, '\', '\\', True);

  SetArrayLength(Lines, 7);
  Lines[0] := '{';
  Lines[1] := '  "name": "{#NativeHostName}",';
  Lines[2] := '  "description": "{#AppName} native messaging host",';
  Lines[3] := '  "path": "' + HostPath + '",';
  Lines[4] := '  "type": "stdio",';
  Lines[5] := '  "allowed_origins": ["chrome-extension://{#ChromeExtensionId}/"]';
  Lines[6] := '}';

  { UTF-8 and no BOM, both load-bearing: the install path may contain non-ASCII
    characters, and Chrome's manifest parser rejects a leading BOM outright. }
  if not SaveStringsToUTF8FileWithoutBOM(Dir + '\{#NativeHostName}.json', Lines, False) then
    MsgBox('Setup could not write the browser bridge manifest to:' + NL + Dir + NL + NL +
           'FDM will still work, but the browser extension will not be able ' +
           'to hand downloads to it. Reinstalling usually fixes this.',
           mbError, MB_OK);
end;

{ ------------------------------------------------------------------ wizard wiring }

procedure InitializeWizard;
begin
  DownloadPage := CreateDownloadPage(
    SetupMessage(msgWizardPreparing),
    'Setup is downloading a component Windows is missing.',
    nil);
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID <> wpReady then
    exit;

  { Nothing missing -> no download page, no network access at all. }
  if WebView2Installed then
    exit;

  DownloadPage.Clear;
  DownloadPage.Add('{#WebView2Url}', 'MicrosoftEdgeWebview2Setup.exe', '');
  DownloadPage.Show;
  try
    try
      DownloadPage.Download;
    except
      { A failed prerequisite download is not a failed install: FDM's engine and
        CLI work without WebView2, only the window does. Let the user continue
        and tell them precisely what to do. }
      if DownloadPage.AbortedByUser then
        Log('WebView2 download cancelled by user.')
      else
        MsgBox('Setup could not download the Microsoft WebView2 runtime:' + NL + NL +
               GetExceptionMessage + NL + NL +
               'Installation will continue. If the FDM window fails to open, install ' +
               'WebView2 from microsoft.com/edge/webview2 and start FDM again.',
               mbInformation, MB_OK);
    end;
  finally
    DownloadPage.Hide;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Installer: String;
  ExitCode: Integer;
begin
  Result := '';
  NeedsRestart := False;

  Installer := ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe');
  if not FileExists(Installer) then
    exit;

  { Microsoft's own silent switches. Failure is non-fatal for the same reason as
    above, so this reports to the log rather than aborting the install. }
  if not Exec(Installer, '/silent /install', '', SW_HIDE, ewWaitUntilTerminated, ExitCode) then
    Log('WebView2 bootstrapper could not be launched.')
  else if ExitCode <> 0 then
    Log('WebView2 bootstrapper exited with code ' + IntToStr(ExitCode) + '.');
end;

procedure WriteExtensionUpdateXml;
var
  Lines: TArrayOfString;
  CrxPath: String;
  Dir: String;
begin
  Dir := ExpandConstant('{app}\extension');
  if not DirExists(Dir) then
    ForceDirectories(Dir);

  CrxPath := 'file:///' + ExpandConstant('{app}\extension\fdm.crx');
  StringChangeEx(CrxPath, '\', '/', True);

  SetArrayLength(Lines, 6);
  Lines[0] := '<?xml version=''1.0'' encoding=''UTF-8''?>';
  Lines[1] := '<gupdate xmlns=''http://www.google.com/update2/response'' protocol=''2.0''>';
  Lines[2] := '  <app appid=''{#ChromeExtensionId}''>';
  Lines[3] := '    <updatecheck codebase=''' + CrxPath + ''' version=''{#AppVersion}'' />';
  Lines[4] := '  </app>';
  Lines[5] := '</gupdate>';

  SaveStringsToUTF8FileWithoutBOM(Dir + '\update.xml', Lines, False);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    WriteNativeHostManifest;
    WriteExtensionUpdateXml;
  end;
end;
