; ============================================================================
;  FDM - Fast Download Manager :: Windows installer
;  Inno Setup 6.3 or newer (needs DownloadTemporaryFile, added in 6.1).
;
;  This is the ONE file an end user ever touches. Compiling this script produces
;  FDM-Setup-<version>.exe, and running that must leave a machine with a working
;  FDM regardless of what was or wasn't already installed. Everything it needs
;  and cannot assume, it fetches.
;
;  Build with:  powershell -ExecutionPolicy Bypass -File scripts\build-installer.ps1
;
;  ASCII only, on purpose: this file has no BOM, and ISCC misreads high bytes in
;  a BOM-less file. That is why the product name uses "-" and not an em dash.
; ============================================================================

#define AppName        "FDM - Fast Download Manager"
#define AppShortName   "FDM"
#define AppPublisher   "Ahmad Farooq"
#define AppUrl         "https://github.com/ahmadfarooq/fdm"
#define AppSupportUrl  "https://github.com/ahmadfarooq/fdm/issues"
#define AppExeName     "fdm-desktop.exe"
#define HostExeName    "fdm-host.exe"
#define CliExeName     "fdm.exe"
#define NativeHostName "com.fdm.native_host"

; Overridable from the command line: ISCC /DAppVersion=0.2.0 installer\fdm.iss
#ifndef AppVersion
  #define AppVersion "0.1.0"
#endif

; Where build-installer.ps1 assembles the payload.
#ifndef StagingDir
  #define StagingDir "..\target\installer-staging"
#endif

; The Chrome Web Store extension ID. Unknown until the extension is published --
; Chrome derives it from the signing key the Store assigns. Until then the
; browser-registration block below is compiled out rather than writing a junk
; registry key that would make Chrome log an error on every launch.
#ifndef ChromeExtensionId
  #define ChromeExtensionId "UNPUBLISHED"
#endif
#define ExtensionPublished (ChromeExtensionId != "UNPUBLISHED")

; Evergreen WebView2 bootstrapper. Permanent Microsoft fwlink, ~1.8 MB; it then
; pulls the full runtime itself. Deliberately not SHA-256 pinned: Microsoft
; reissues this file, and a pinned hash would turn every reissue into a broken
; installer for every user at once. The URL is HTTPS to a Microsoft host and the
; payload is Authenticode-signed by Microsoft, which is the real integrity gate.
#define WebView2Url "https://go.microsoft.com/fwlink/p/?LinkId=2124703"

[Setup]
; Never change AppId. It is how Windows recognises an upgrade rather than a
; second parallel installation.
AppId={{8B7F3A21-4D6E-4C1B-9E5A-2F0D7C6B4A19}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription={#AppName} Setup
AppPublisher={#AppPublisher}
AppPublisherURL={#AppUrl}
AppSupportURL={#AppSupportUrl}
AppUpdatesURL={#AppUrl}/releases
DefaultDirName={autopf}\FDM
DefaultGroupName=FDM
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\{#CliExeName}
LicenseFile=..\LICENSE
OutputDir=output
OutputBaseFilename=FDM-Setup-{#AppVersion}
SetupIconFile=assets\fdm.ico
WizardStyle=modern
WizardImageFile=assets\wizard-large.bmp
WizardSmallImageFile=assets\wizard-small.bmp
WizardImageStretch=no

; Admin: the native messaging host and the browser extension policy both live
; under HKLM. A per-user install would have to write HKCU, which breaks the
; moment the browser runs under a different integrity level.
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; If FDM is running, close it rather than leaving locked files behind. The mutex
; name must match the one the desktop app creates for single-instance.
AppMutex=FdmSingleInstanceMutex
CloseApplications=yes
RestartApplications=no

Compression=lzma2/max
SolidCompression=yes
LZMAUseSeparateProcess=yes
DisableProgramGroupPage=yes
DisableDirPage=no
ShowLanguageDialog=no
MinVersion=10.0.17763

; Code signing. Enabled by build-installer.ps1 -SignThumbprint / -SelfSign,
; which passes /DSignToolName=fdmsign together with /Sfdmsign="<command>".
;
; This block exists for one reason: the uninstaller. Setup.exe can be signed
; afterwards with signtool, but unins000.exe is generated by Setup at install
; time on the user's machine, so only Inno can arrange for it to be signed --
; it embeds a pre-signed copy. Without this, Add/Remove Programs > Uninstall
; raises a UAC prompt reading "Publisher: Unknown" even on a signed install.
#ifdef SignToolName
SignTool={#SignToolName}
SignedUninstaller=yes
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Shortcuts:"
Name: "startup"; Description: "Start FDM when I sign in to Windows"; GroupDescription: "Startup:"
Name: "addtopath"; Description: "Add the &fdm command to PATH (for terminal use)"; GroupDescription: "Advanced:"; Flags: unchecked

[Files]
; --- Engine and CLI. Always present; the build script refuses to run without it.
Source: "{#StagingDir}\{#CliExeName}"; DestDir: "{app}"; Flags: ignoreversion

; --- Desktop app and native messaging host. Marked skipifsourcedoesntexist so
;     this script compiles during Phase 1/2 development; build-installer.ps1
;     prints exactly which of them made it into a given build, and refuses to
;     produce a release build without them.
Source: "{#StagingDir}\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#StagingDir}\{#HostExeName}"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#StagingDir}\WebView2Loader.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist

; --- Unpacked extension. Ships even when the Store version is registered: it is
;     the fallback for Chromium builds without Store access, and the thing a
;     developer loads via chrome://extensions -> Load unpacked.
Source: "{#StagingDir}\extension\*"; DestDir: "{app}\extension"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist

Source: "..\LICENSE"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion
Source: "..\README.md"; DestDir: "{app}"; DestName: "README.md"; Flags: ignoreversion skipifsourcedoesntexist

[Dirs]
; The generated native messaging manifest lands here.
Name: "{app}\manifests"

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Check: HasDesktopApp
Name: "{group}\Uninstall {#AppShortName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppShortName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon; Check: HasDesktopApp

[Registry]
; ---------------------------------------------------------------- uninstall key
Root: HKLM; Subkey: "Software\FDM"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"; Flags: uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\FDM"; ValueType: string; ValueName: "Version"; ValueData: "{#AppVersion}"; Flags: uninsdeletekey

; ------------------------------------------------- native messaging host, HKLM
; One key per Chromium family. They do not share a namespace, so a user on Brave
; gets nothing from the Chrome key. All point at the same generated manifest.
; Written to both registry views: a 32-bit browser on 64-bit Windows reads the
; WOW6432Node view and would not see a 64-bit-only key.
Root: HKLM32; Subkey: "Software\Google\Chrome\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\Google\Chrome\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM32; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\BraveSoftware\Brave-Browser\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\Vivaldi\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost
Root: HKLM64; Subkey: "Software\Chromium\NativeMessagingHosts\{#NativeHostName}"; ValueType: string; ValueData: "{app}\manifests\{#NativeHostName}.json"; Flags: uninsdeletekey; Check: HasNativeHost

; ------------------------------------------------------- extension pre-install
; This is the closest thing Windows allows to "install the extension for them".
; It tells Chrome the extension exists and where to update from; Chrome then
; shows the user a one-time enable prompt. Silent sideloading of a local .crx
; has been blocked since Chrome 33 and there is no way around it -- the honest
; framing is one click to install, one click to enable.
#if ExtensionPublished
Root: HKLM32; Subkey: "Software\Google\Chrome\Extensions\{#ChromeExtensionId}"; ValueType: string; ValueName: "update_url"; ValueData: "https://clients2.google.com/service/update2/crx"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Google\Chrome\Extensions\{#ChromeExtensionId}"; ValueType: string; ValueName: "update_url"; ValueData: "https://clients2.google.com/service/update2/crx"; Flags: uninsdeletekey
#endif

; ------------------------------------------------------------------- run-at-login
; HKCU under elevation resolves to the account that approved the UAC prompt. On
; the normal case (the signed-in user is a local admin) that is the same account.
; When it isn't, the app's own Settings toggle is the authoritative control, and
; it writes this same value from a non-elevated process.
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "FDM"; ValueData: """{app}\{#AppExeName}"" --minimized"; Flags: uninsdeletevalue; Tasks: startup; Check: HasDesktopApp

; ------------------------------------------------------------------------- PATH
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Tasks: addtopath; Check: NeedsAddPath(ExpandConstant('{app}'))

[Run]
; Create Downloads\FDM\{Documents,Video,Music,Images,Compressed,Programs,Other}.
; runasoriginaluser is the whole point: without it the folders would be created
; in the elevating administrator's profile, not the user's.
Filename: "{app}\{#CliExeName}"; Parameters: "init-folders"; Flags: runasoriginaluser runhidden waituntilterminated; StatusMsg: "Creating your download folders..."

Filename: "{app}\{#AppExeName}"; Description: "Launch {#AppShortName} now"; Flags: nowait postinstall skipifsilent runasoriginaluser; Check: HasDesktopApp
Filename: "https://github.com/ahmadfarooq/fdm#enabling-the-browser-extension"; Description: "Show me how to enable the browser extension"; Flags: nowait postinstall shellexec skipifsilent unchecked

[UninstallDelete]
; Generated at install time, so not tracked by the file list.
Type: files; Name: "{app}\manifests\{#NativeHostName}.json"
Type: dirifempty; Name: "{app}\manifests"
Type: dirifempty; Name: "{app}"

[Messages]
WelcomeLabel2=This will install [name/ver] on your computer.%n%nFDM splits every download across many connections and writes them straight to disk, so there is no reassembly step and a crash resumes instead of restarting.%n%nSetup will also install anything missing that FDM needs, including the Microsoft WebView2 runtime.
FinishedLabelNoIcons=Setup finished installing [name].
FinishedLabel=Setup finished installing [name].%n%nOne last step, and it is Chrome's rule rather than ours: open your browser and click Enable when it asks about the FDM extension. Chrome does not allow any installer to enable an extension for you.

[Code]
{ ISPP treats any line whose first non-whitespace character is '#' as a
  preprocessor directive -- including inside [Code]. A wrapped Pascal expression
  that happens to begin with #13#10 therefore fails to compile with "Unknown
  preprocessor directive". Naming the newline once avoids the trap entirely. }
const
  NL = #13#10;

var
  DownloadPage: TDownloadWizardPage;

{ ------------------------------------------------------------------ payload probes }
{ The desktop app and native host are built in later phases. Rather than shipping
  shortcuts to a file that isn't there, every dependent entry is gated on the
  file actually having been installed. }

function HasDesktopApp: Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\{#AppExeName}'));
end;

function HasNativeHost: Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\{#HostExeName}'));
end;

{ --------------------------------------------------------------------------- PATH }

function NeedsAddPath(Param: String): Boolean;
var
  OrigPath: String;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath) then
  begin
    Result := True;
    exit;
  end;
  { Semicolon-delimited on both sides so "C:\Program Files\FDM" does not match
    "C:\Program Files\FDMx". }
  Result := Pos(';' + Uppercase(Param) + ';', ';' + Uppercase(OrigPath) + ';') = 0;
end;

{ ---------------------------------------------------------------- WebView2 runtime }
{ The Evergreen runtime registers its version under EdgeUpdate Clients with this
  fixed GUID. Machine-wide installs land in HKLM (and in the 32-bit view even on
  64-bit Windows); per-user installs land in HKCU. A non-empty 'pv' means present.
  Windows 11 ships it, so on most machines this returns True and nothing is
  downloaded at all. }

function WebView2Installed: Boolean;
var
  Version: String;
  ClientKey: String;
begin
  Result := False;
  { The Evergreen runtime's fixed product GUID. Not a placeholder -- Microsoft
    ships this exact value on every machine that has WebView2. }
  ClientKey := 'Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';

  if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\WOW6432Node\' + ClientKey, 'pv', Version) then
    if (Version <> '') and (Version <> '0.0.0.0') then
    begin
      Result := True;
      exit;
    end;

  if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\' + ClientKey, 'pv', Version) then
    if (Version <> '') and (Version <> '0.0.0.0') then
    begin
      Result := True;
      exit;
    end;

  if RegQueryStringValue(HKEY_CURRENT_USER, 'SOFTWARE\' + ClientKey, 'pv', Version) then
    if (Version <> '') and (Version <> '0.0.0.0') then
      Result := True;
end;

{ ------------------------------------------------- native messaging host manifest }
{ Written at install time rather than shipped, because 'path' has to be the real
  absolute install path and 'allowed_origins' has to match the published
  extension ID. Chrome refuses to start a host whose manifest lists an origin
  that does not match the calling extension, so a wrong value here is a silent
  "extension can't reach FDM" bug. }

procedure WriteNativeHostManifest;
var
  Lines: TArrayOfString;
  HostPath: String;
  Dir: String;
begin
  if not HasNativeHost then
    exit;

  Dir := ExpandConstant('{app}\manifests');
  if not DirExists(Dir) then
    ForceDirectories(Dir);

  { JSON needs backslashes escaped. }
  HostPath := ExpandConstant('{app}\{#HostExeName}');
  StringChangeEx(HostPath, '\', '\\', True);

  SetArrayLength(Lines, 7);
  Lines[0] := '{';
  Lines[1] := '  "name": "{#NativeHostName}",';
  Lines[2] := '  "description": "{#AppName} native messaging host",';
  Lines[3] := '  "path": "' + HostPath + '",';
  Lines[4] := '  "type": "stdio",';
  Lines[5] := '  "allowed_origins": ["chrome-extension://{#ChromeExtensionId}/"]';
  Lines[6] := '}';

  { UTF-8 and no BOM, both load-bearing: the install path may contain non-ASCII
    characters, and Chrome's manifest parser rejects a leading BOM outright. }
  if not SaveStringsToUTF8FileWithoutBOM(Dir + '\{#NativeHostName}.json', Lines, False) then
    MsgBox('Setup could not write the browser bridge manifest to:' + NL + Dir + NL + NL +
           'FDM will still work, but the browser extension will not be able ' +
           'to hand downloads to it. Reinstalling usually fixes this.',
           mbError, MB_OK);
end;

{ ------------------------------------------------------------------ wizard wiring }

procedure InitializeWizard;
begin
  DownloadPage := CreateDownloadPage(
    SetupMessage(msgWizardPreparing),
    'Setup is downloading a component Windows is missing.',
    nil);
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID <> wpReady then
    exit;

  { Nothing missing -> no download page, no network access at all. }
  if WebView2Installed then
    exit;

  DownloadPage.Clear;
  DownloadPage.Add('{#WebView2Url}', 'MicrosoftEdgeWebview2Setup.exe', '');
  DownloadPage.Show;
  try
    try
      DownloadPage.Download;
    except
      { A failed prerequisite download is not a failed install: FDM's engine and
        CLI work without WebView2, only the window does. Let the user continue
        and tell them precisely what to do. }
      if DownloadPage.AbortedByUser then
        Log('WebView2 download cancelled by user.')
      else
        MsgBox('Setup could not download the Microsoft WebView2 runtime:' + NL + NL +
               GetExceptionMessage + NL + NL +
               'Installation will continue. If the FDM window fails to open, install ' +
               'WebView2 from microsoft.com/edge/webview2 and start FDM again.',
               mbInformation, MB_OK);
    end;
  finally
    DownloadPage.Hide;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Installer: String;
  ExitCode: Integer;
begin
  Result := '';
  NeedsRestart := False;

  Installer := ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe');
  if not FileExists(Installer) then
    exit;

  { Microsoft's own silent switches. Failure is non-fatal for the same reason as
    above, so this reports to the log rather than aborting the install. }
  if not Exec(Installer, '/silent /install', '', SW_HIDE, ewWaitUntilTerminated, ExitCode) then
    Log('WebView2 bootstrapper could not be launched.')
  else if ExitCode <> 0 then
    Log('WebView2 bootstrapper exited with code ' + IntToStr(ExitCode) + '.');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    WriteNativeHostManifest;
end;
